"""W0: problem definition, data padding, bucket sizes."""

import numpy as np
import pytest

from gcbml._config import bucket
from gcbml.data import Dataset, Probe, RunResult
from gcbml.problem import InputSpace, Problem, ResolutionComponent, ResolutionSpec, Tolerance


def _problem():
    inputs = InputSpace(("a", "b", "v"), (0.0, 10.0, 0.5), (1.0, 20.0, 0.95), n_controls=2)
    res = ResolutionSpec((ResolutionComponent("dx", (1.0, 0.5, 0.25)),))
    return Problem(inputs, res, Tolerance(rel=0.1), budget=100.0)


def test_bucket_is_at_least_n_and_monotone():
    """Every bucket holds n, and buckets never shrink as n grows."""
    sizes = [bucket(n) for n in range(1, 5000)]
    assert all(s >= n for n, s in zip(range(1, 5000), sizes))
    assert all(b >= a for a, b in zip(sizes, sizes[1:]))
    assert len(set(sizes)) < 60  # few distinct shapes, so few recompilations


def test_unit_scaling_round_trip():
    """to_unit and from_unit are inverse maps."""
    p = _problem()
    x = np.array([[0.3, 12.0, 0.7]])
    assert np.allclose(p.inputs.from_unit(p.inputs.to_unit(x)), x)


def test_sigma_n_is_100d_points_inside_unit_cube():
    """Sigma_N has 100 d points in [0, 1]^d (spec Section 1)."""
    p = _problem()
    assert p.sigma_n.shape == (300, 3)
    assert p.sigma_n.min() >= 0 and p.sigma_n.max() <= 1


def test_resolution_levels_extend_beyond_listed_values():
    """Finer levels than listed are generated by the refinement ratio; h_c never changes."""
    c = ResolutionComponent("dx", (1.0, 0.5, 0.25))
    assert c.level_value(4) == pytest.approx(0.0625)
    assert c.h_c == 1.0


def test_invalid_inputs_raise():
    with pytest.raises(ValueError):
        ResolutionComponent("dx", (0.5, 1.0))
    with pytest.raises(ValueError):
        Tolerance()
    with pytest.raises(ValueError):
        InputSpace(("a",), (1.0,), (0.0,), 1)


def test_padded_dataset_masks_padding_rows():
    """Padded rows are masked and carry run index -1; real rows keep their values."""
    p = _problem()
    ds = Dataset()
    for i, h in enumerate((1.0, 0.5)):
        x = np.array([[0.2, 15.0, 0.5], [0.2, 15.0, 0.9]])
        ds.add(
            RunResult(
                Probe(f"r{i}", (0.2, 15.0), (h,)),
                x,
                np.array([1.0 + i, 2.0 + i]),
                np.array([False, True]),
                cost=1.0,
            )
        )
    pd = ds.padded(p.inputs.to_unit, p.resolution.hbar)
    assert pd.n == 4 and pd.mask.size == bucket(4)
    assert np.array_equal(pd.run[:4], [0, 0, 1, 1]) and np.all(pd.run[4:] == -1)
    assert np.allclose(pd.H[:4, 0], [1.0, 1.0, 0.5, 0.5])
    assert pd.censored[1] and not pd.censored[4:].any()
